"""Add latitude and longitude to Transaction model

Revision ID: 58c9a75f9ada
Revises: be84c218d64d
Create Date: 2026-02-17 05:58:34.782203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c9a75f9ada'
down_revision: Union[str, Sequence[str], None] = 'be84c218d64d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'longitude')
    op.drop_column('transactions', 'latitude')
    # ### end Alembic commands ###
