"""Update VirtualCard model and User relationship (final attempt)

Revision ID: 63d4e69ec360
Revises: f5128c9c4b92
Create Date: 2026-02-17 07:51:14.235768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d4e69ec360'
down_revision: Union[str, Sequence[str], None] = 'f5128c9c4b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema for SQLite compatibility."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a SQLite-compatible migration for adding columns with NOT NULL and UNIQUE constraints
    # and establishing relationships.

    # 1. Create a new temporary table with the desired schema
    op.create_table(
        'virtualcards_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True), # Temporarily nullable for data copy
        sa.Column('card_number', sa.String(), nullable=False), # New NOT NULL
        sa.Column('expiry_date', sa.String(), nullable=False), # New NOT NULL
        sa.Column('cvv_hashed', sa.String(), nullable=False), # New NOT NULL
        sa.Column('currency', sa.String(), nullable=True, server_default='USD'),
        sa.Column('balance', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('spending_limit', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('status', sa.String(), nullable=True, server_default='active'),
        sa.Column('type', sa.String(), nullable=False, server_default='rechargeable'), # New NOT NULL
        sa.Column('issuance_fee_paid', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('provider_card_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('card_number'), # New UNIQUE constraint
        sa.UniqueConstraint('provider_card_id')
    )
    op.create_index(op.f('ix_virtualcards_new_id'), 'virtualcards_new', ['id'], unique=False)

    # 2. Copy data from old 'virtualcards' to 'virtualcards_new'
    #    Provide default values for new NOT NULL columns during copy
    op.execute(
        """INSERT INTO virtualcards_new (id, user_id, card_number, currency, balance,
                                        spending_limit, status, issuance_fee_paid,
                                        provider_card_id, created_at, updated_at,
                                        expiry_date, cvv_hashed, type)
           SELECT id, user_id, card_number, currency, balance,
                  spending_limit, status, issuance_fee_paid,
                  provider_card_id, created_at, updated_at,
                  '01/99', 'dummy_cvv_hash', 'rechargeable'
           FROM virtualcards"""
    )

    # 3. Drop the old 'virtualcards' table
    op.drop_table('virtualcards')

    # 4. Rename 'virtualcards_new' to 'virtualcards'
    op.rename_table('virtualcards_new', 'virtualcards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema for SQLite compatibility."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a SQLite-compatible downgrade

    # 1. Create a new temporary table with the original schema
    op.create_table(
        'virtualcards_old',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('card_number', sa.String(), nullable=True), # Original nullable
        sa.Column('currency', sa.String(), nullable=True, server_default='USD'),
        sa.Column('balance', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('spending_limit', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('status', sa.String(), nullable=True, server_default='active'),
        sa.Column('issuance_fee_paid', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('provider_card_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtualcards_old_id'), 'virtualcards_old', ['id'], unique=False)

    # 2. Copy data back from 'virtualcards' to 'virtualcards_old'
    op.execute(
        """INSERT INTO virtualcards_old (id, user_id, card_number, currency, balance,
                                        spending_limit, status, issuance_fee_paid,
                                        provider_card_id)
           SELECT id, user_id, card_number, currency, balance,
                  spending_limit, status, issuance_fee_paid,
                  provider_card_id
           FROM virtualcards"""
    )

    # 3. Drop the new 'virtualcards' table
    op.drop_table('virtualcards')

    # 4. Rename 'virtualcards_old' to 'virtualcards'
    op.rename_table('virtualcards_old', 'virtualcards')
    # ### end Alembic commands ###