"""Add is_borrowing_frozen to Agent and is_frozen to Wallet

Revision ID: 7ed157f6f63d
Revises: 58c9a75f9ada
Create Date: 2026-02-17 06:33:15.231342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed157f6f63d'
down_revision: Union[str, Sequence[str], None] = '58c9a75f9ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_borrowing_frozen', sa.Boolean(), nullable=True))
    op.add_column('wallets', sa.Column('is_frozen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'is_frozen')
    op.drop_column('agents', 'is_borrowing_frozen')
    # ### end Alembic commands ###
