"""Add loan offer fields to LoanApplication

Revision ID: be84c218d64d
Revises: 45529e604580
Create Date: 2026-02-17 05:44:01.272462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be84c218d64d'
down_revision: Union[str, Sequence[str], None] = '45529e604580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('approved_amount', sa.Float(), nullable=True))
    op.add_column('loan_applications', sa.Column('fee_percentage', sa.Float(), nullable=True))
    op.add_column('loan_applications', sa.Column('offered_repayment_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'offered_repayment_duration')
    op.drop_column('loan_applications', 'fee_percentage')
    op.drop_column('loan_applications', 'approved_amount')
    # ### end Alembic commands ###
