"""Implement AI Credit Scoring Engine tables and logic

Revision ID: f5128c9c4b92
Revises: 7ed157f6f63d
Create Date: 2026-02-17 07:03:38.633863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5128c9c4b92'
down_revision: Union[str, Sequence[str], None] = '7ed157f6f63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_risk_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('recommended_limit', sa.Float(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_risk_profiles_agent_id'), 'agent_risk_profiles', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agent_risk_profiles_id'), 'agent_risk_profiles', ['id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_agent_id'), 'risk_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_risk_events_id'), 'risk_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_agent_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_agent_risk_profiles_id'), table_name='agent_risk_profiles')
    op.drop_index(op.f('ix_agent_risk_profiles_agent_id'), table_name='agent_risk_profiles')
    op.drop_table('agent_risk_profiles')
    # ### end Alembic commands ###
