from __future__ import annotations

from api.client import API_URL, DEFAULT_TIMEOUT, FAST_TIMEOUT


APP_NAME = "Cyber Cash"
DEFAULT_CURRENCY = "GH¢"
DEFAULT_CURRENCY_CODE = "GHS"
DEFAULT_HOME_TRANSACTION_LIMIT = 3
DEFAULT_NOTIFICATION_LIMIT = 10
DEFAULT_TRANSACTION_LIMIT = 20
DASHBOARD_REFRESH_SECONDS = 30


__all__ = [
    "API_URL",
    "APP_NAME",
    "DEFAULT_CURRENCY",
    "DEFAULT_CURRENCY_CODE",
    "DEFAULT_HOME_TRANSACTION_LIMIT",
    "DEFAULT_NOTIFICATION_LIMIT",
    "DEFAULT_TIMEOUT",
    "DEFAULT_TRANSACTION_LIMIT",
    "DASHBOARD_REFRESH_SECONDS",
    "FAST_TIMEOUT",
]
